site_name: NIR 4 Scala
repo_url: https://github.com/mrontio/nir4s
site_url: https://mront.io/nir4s/


theme:
  name: readthedocs

nav:
  - Home: index.md
  - Guide:
    - Installation: guide/installation.md
    - Importing a NIR Graph: guide/import.md
    - Using a NIR Graph: guide/using.md

  - API Reference: api/
