name: docs
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: sbt/setup-sbt@v1
      - run: sbt doc

      # install mkdocs
      - run: pip install mkdocs mkdocs-material

      # copy scaladoc into docs/api
      - run: |
          mkdir -p docs/api
          cp -r target/scala-*/api/* docs/api/

      # build MkDocs site
      - run: mkdocs build --site-dir site
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
